version: '3'

services:
  mcp-freecad:
    build: .
    ports:
      - "8080:8080"
      - "12345:12345"
    volumes:
      - ./:/app
    environment:
      - PYTHONPATH=/app
    restart: unless-stopped
